# AI-Powered Enterprise Workflow Agent Configuration

# Application Information
app:
  name: "AI-Powered Enterprise Workflow Agent"
  version: "1.0"
  owner: "Dinesh Reddy"
  description: "Intelligent workflow automation system for enterprise operations"

# LLM Configuration
llm:
  default_provider: "openai"  # openai, groq, anthropic
  models:
    openai:
      default: "gpt-4"
      classification: "gpt-3.5-turbo"
      assignment: "gpt-4"
      reporting: "gpt-4"
    groq:
      default: "llama3-70b-8192"
      classification: "llama3-8b-8192"
      assignment: "llama3-70b-8192"
      reporting: "llama3-70b-8192"
  temperature: 0.1
  max_tokens: 2000
  timeout: 30

# Database Configuration
database:
  url: "sqlite:///./data/workflow_agent.db"
  echo: false
  pool_size: 10
  max_overflow: 20

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1
  cors_origins:
    - "http://localhost:8501"
    - "http://127.0.0.1:8501"

# Streamlit Configuration
streamlit:
  host: "localhost"
  port: 8501
  theme: "light"

# Vector Store Configuration
vector_store:
  type: "faiss"
  path: "./data/vector_store"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  dimension: 384

# Classification Configuration
classification:
  categories:
    - "IT"
    - "HR" 
    - "Operations"
  priorities:
    - "Critical"
    - "High"
    - "Medium"
    - "Low"
  confidence_threshold: 0.8
  min_confidence: 0.6

# Assignment Configuration
assignment:
  strategy: "skill_based"  # skill_based, round_robin, workload_based
  confidence_threshold: 0.75
  teams:
    IT:
      - "DevOps Team"
      - "Infrastructure Team"
      - "Security Team"
      - "Application Support"
    HR:
      - "Recruitment Team"
      - "Employee Relations"
      - "Payroll Team"
      - "Training & Development"
    Operations:
      - "Project Management"
      - "Quality Assurance"
      - "Business Analysis"
      - "Process Improvement"

# Report Configuration
reports:
  output_dir: "./reports"
  template_dir: "./templates"
  formats:
    - "pdf"
    - "html"
    - "json"
  charts:
    enabled: true
    library: "plotly"  # plotly, matplotlib
  
# Logging Configuration
logging:
  level: "INFO"
  file: "./logs/workflow_agent.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  rotation: "1 day"
  retention: "30 days"

# Performance Monitoring
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30

# Enterprise Integration (Mock for v1.0)
enterprise:
  mock_mode: true
  itsm:
    enabled: true
    api_url: "http://mock-itsm.local"
  hrms:
    enabled: true
    api_url: "http://mock-hrms.local"
  operations:
    enabled: true
    api_url: "http://mock-ops.local"

# Security Configuration
security:
  secret_key: "your-secret-key-here"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# Development Settings
development:
  debug: true
  testing: false
  mock_data: true
  auto_reload: true
